apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discord-ai-bot.fullname" . }}-bot
  labels:
    {{- include "discord-ai-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "discord-ai-bot.selectorLabels" . | nindent 6 }}
      component: bot
  template:
    metadata:
      labels:
        {{- include "discord-ai-bot.selectorLabels" . | nindent 8 }}
        component: bot
    spec:
      containers:
        - name: bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DISCORD_TOKEN
              value: {{ .Values.bot.env.DISCORD_TOKEN | quote }}
            - name: MODEL_API_URL
              value: {{ .Values.bot.env.MODEL_API_URL | quote }}
          resources:
            {{- toYaml .Values.bot.resources | nindent 12 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discord-ai-bot.fullname" . }}-api
  labels:
    {{- include "discord-ai-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "discord-ai-bot.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      labels:
        {{- include "discord-ai-bot.selectorLabels" . | nindent 8 }}
        component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: {{ .Values.api.env.MODEL_PATH | quote }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5