apiVersion: v1
kind: Service
metadata:
  name: {{ include "discord-ai-bot.fullname" . }}-api
  labels:
    {{- include "discord-ai-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "discord-ai-bot.selectorLabels" . | nindent 4 }}
    component: api

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "discord-ai-bot.fullname" . }}-monitoring
  labels:
    {{- include "discord-ai-bot.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "discord-ai-bot.selectorLabels" . | nindent 4 }}
    component: api