apiVersion: v2
name: discord-ai-bot
description: A Helm chart for deploying Discord AI Bot with custom NLP model
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: redis
  version: 14.8.8
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled